In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
a = np.array([1, 3, 5, 7, 9])

In [7]:
a

array([1, 3, 5, 7, 9])

In [8]:
a[2]

5

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  3, 10,  7,  9])

In [11]:
a = np.arange(3,10)

In [12]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0 ,1 ,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[1][2]

6

In [21]:
n[2] = [1, 1, 1]

In [22]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [23]:
n[:, 1]

array([2, 5, 1])

In [24]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [25]:
n[1:]

array([[4, 5, 6],
       [1, 1, 1]])

In [28]:
n[:, 2] = [0, 1, 2]

In [29]:
n

array([[0, 1, 0],
       [0, 1, 1],
       [1, 1, 2]])

In [30]:
n=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
n[:, 2] = [0, 1, 2]

In [32]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [33]:
n=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
n[: 2] = [0, 1, 2]

In [3]:
np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NameError: name 'np' is not defined

In [2]:
np.random.seed(2)
100 * np.random.rand(5, 2)

NameError: name 'np' is not defined

In [1]:
np.random.randint(low=0, high=100, size=(5, 2))

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
np.random.randint(low=0, high=100, size=(5, 2))


array([[70, 97],
       [92, 60],
       [91, 38],
       [32, 84],
       [52, 42]])

In [6]:
a = np.arange(5)

In [7]:
a


array([0, 1, 2, 3, 4])

In [8]:
a+1

array([1, 2, 3, 4, 5])

In [9]:
a*2

array([0, 2, 4, 6, 8])

In [11]:
b = 10 + (a/2)

In [12]:
b

array([10. , 10.5, 11. , 11.5, 12. ])

In [13]:
a + b

array([10. , 11.5, 13. , 14.5, 16. ])

In [14]:
a >= 1

array([False,  True,  True,  True,  True])

In [15]:
a >= b

array([False, False, False, False, False])

In [16]:
b[b > a]

array([10. , 10.5, 11. , 11.5, 12. ])

In [18]:
a[a > b]

array([], dtype=int64)

In [19]:
a[max]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [20]:
a(max)

TypeError: 'numpy.ndarray' object is not callable

In [21]:
a.max()

4

In [22]:
b.max()

12.0

In [23]:
a.sum()

10

In [24]:
b.sum()

55.0

In [25]:
a.std()

1.4142135623730951

In [26]:
a.min()

0

In [27]:
b.min()

10.0